const fs = require('fs');
const {parse} = require('csv-parse');

const nameToAlpha03map = new Map();

nameToAlpha03map.set("Aruba", "ABW");
nameToAlpha03map.set("Afghanistan", "AFG");
nameToAlpha03map.set("Angola", "AGO");
nameToAlpha03map.set("Anguilla", "AIA");
nameToAlpha03map.set("Åland Islands", "ALA");
nameToAlpha03map.set("Albania", "ALB");
nameToAlpha03map.set("Andorra", "AND");
nameToAlpha03map.set("United Arab Emirates", "ARE");
nameToAlpha03map.set("Argentina", "ARG");
nameToAlpha03map.set("Armenia", "ARM");
nameToAlpha03map.set("American Samoa", "ASM");
nameToAlpha03map.set("Antarctica", "ATA");
nameToAlpha03map.set("French Southern Territories", "ATF");
nameToAlpha03map.set("Antigua and Barbuda", "ATG");
nameToAlpha03map.set("Australia", "AUS");
nameToAlpha03map.set("Austria", "AUT");
nameToAlpha03map.set("Azerbaijan", "AZE");
nameToAlpha03map.set("Burundi", "BDI");
nameToAlpha03map.set("Belgium", "BEL");
nameToAlpha03map.set("Benin", "BEN");
nameToAlpha03map.set("Bonaire, Sint Eustatius and Saba", "BES");
nameToAlpha03map.set("Burkina Faso", "BFA");
nameToAlpha03map.set("Bangladesh", "BGD");
nameToAlpha03map.set("Bulgaria", "BGR");
nameToAlpha03map.set("Bahrain", "BHR");
nameToAlpha03map.set("Bahamas", "BHS");
nameToAlpha03map.set("Bosnia and Herzegovina", "BIH");
nameToAlpha03map.set("Saint Barthélemy", "BLM");
nameToAlpha03map.set("Belarus", "BLR");
nameToAlpha03map.set("Belize", "BLZ");
nameToAlpha03map.set("Bermuda", "BMU");
nameToAlpha03map.set("Bolivia", "BOL");
nameToAlpha03map.set("Brazil", "BRA");
nameToAlpha03map.set("Barbados", "BRB");
nameToAlpha03map.set("Brunei", "BRN");
nameToAlpha03map.set("Bhutan", "BTN");
nameToAlpha03map.set("Bouvet Island", "BVT");
nameToAlpha03map.set("Botswana", "BWA");
nameToAlpha03map.set("Central African Republic", "CAF");
nameToAlpha03map.set("Canada", "CAN");
nameToAlpha03map.set("Cocos (Keeling) Islands", "CCK");
nameToAlpha03map.set("Switzerland", "CHE");
nameToAlpha03map.set("Chile", "CHL");
nameToAlpha03map.set("China", "CHN");
nameToAlpha03map.set("Ivory Coast", "CIV");
nameToAlpha03map.set("Cote d'Ivoire", "CIV");
nameToAlpha03map.set("Côte d'Ivoire (Ivory Coast)", "CIV");
nameToAlpha03map.set("Cameroon", "CMR");
nameToAlpha03map.set("DR Congo", "COD");
nameToAlpha03map.set("Congo, Democratic Republic of the", "COD");
nameToAlpha03map.set("Democratic Republic of the Congo", "COD");
nameToAlpha03map.set("Congo", "COG");
nameToAlpha03map.set("Congo, Republic of the", "COG");
nameToAlpha03map.set("Republic of the Congo", "COG");
nameToAlpha03map.set("Cook Islands", "COK");
nameToAlpha03map.set("Colombia", "COL");
nameToAlpha03map.set("Comoros", "COM");
nameToAlpha03map.set("Cabo Verde", "CPV");
nameToAlpha03map.set("Cape Verde", "CPV");
nameToAlpha03map.set("Costa Rica", "CRI");
nameToAlpha03map.set("Cuba", "CUB");
nameToAlpha03map.set("Curaçao", "CUW");
nameToAlpha03map.set("Christmas Island", "CXR");
nameToAlpha03map.set("Cayman Islands", "CYM");
nameToAlpha03map.set("Cyprus", "CYP");
nameToAlpha03map.set("Czechia", "CZE");
nameToAlpha03map.set("Czech Republic", "CZE");
nameToAlpha03map.set("Germany", "DEU");
nameToAlpha03map.set("Djibouti", "DJI");
nameToAlpha03map.set("Dominica", "DMA");
nameToAlpha03map.set("Denmark", "DNK");
nameToAlpha03map.set("Dominican Republic", "DOM");
nameToAlpha03map.set("Algeria", "DZA");
nameToAlpha03map.set("Ecuador", "ECU");
nameToAlpha03map.set("Egypt", "EGY");
nameToAlpha03map.set("Eritrea", "ERI");
nameToAlpha03map.set("Western Sahara", "ESH");
nameToAlpha03map.set("Spain", "ESP");
nameToAlpha03map.set("Estonia", "EST");
nameToAlpha03map.set("Ethiopia", "ETH");
nameToAlpha03map.set("Finland", "FIN");
nameToAlpha03map.set("Fiji", "FJI");
nameToAlpha03map.set("Falkland Islands (Malvinas)", "FLK");
nameToAlpha03map.set("France", "FRA");
nameToAlpha03map.set("Faroe Islands", "FRO");
nameToAlpha03map.set("Micronesia", "FSM");
nameToAlpha03map.set("Micronesia, Federated States of", "FSM");
nameToAlpha03map.set("Federated States of Micronesia", "FSM");
nameToAlpha03map.set("Gabon", "GAB");
nameToAlpha03map.set("United Kingdom", "GBR");
nameToAlpha03map.set("Georgia", "GEO");
nameToAlpha03map.set("Guernsey", "GGY");
nameToAlpha03map.set("Ghana", "GHA");
nameToAlpha03map.set("Gibraltar", "GIB");
nameToAlpha03map.set("Guinea", "GIN");
nameToAlpha03map.set("Guadeloupe", "GLP");
nameToAlpha03map.set("Gambia", "GMB");
nameToAlpha03map.set("The Gambia", "GMB");
nameToAlpha03map.set("Guinea-Bissau", "GNB");
nameToAlpha03map.set("Equatorial Guinea", "GNQ");
nameToAlpha03map.set("Greece", "GRC");
nameToAlpha03map.set("Grenada", "GRD");
nameToAlpha03map.set("Greenland", "GRL");
nameToAlpha03map.set("Guatemala", "GTM");
nameToAlpha03map.set("French Guiana", "GUF");
nameToAlpha03map.set("Guam", "GUM");
nameToAlpha03map.set("Guyana", "GUY");
nameToAlpha03map.set("Hong Kong", "HKG");
nameToAlpha03map.set("Heard Island and McDonald Islands", "HMD");
nameToAlpha03map.set("Honduras", "HND");
nameToAlpha03map.set("Croatia", "HRV");
nameToAlpha03map.set("Haiti", "HTI");
nameToAlpha03map.set("Hungary", "HUN");
nameToAlpha03map.set("Indonesia", "IDN");
nameToAlpha03map.set("Isle of Man", "IMN");
nameToAlpha03map.set("India", "IND");
nameToAlpha03map.set("British Indian Ocean Territory", "IOT");
nameToAlpha03map.set("Ireland", "IRL");
nameToAlpha03map.set("Iran", "IRN");
nameToAlpha03map.set("Iraq", "IRQ");
nameToAlpha03map.set("Iceland", "ISL");
nameToAlpha03map.set("Israel", "ISR");
nameToAlpha03map.set("Italy", "ITA");
nameToAlpha03map.set("Jamaica", "JAM");
nameToAlpha03map.set("Jersey", "JEY");
nameToAlpha03map.set("Jordan", "JOR");
nameToAlpha03map.set("Japan", "JPN");
nameToAlpha03map.set("Kazakhstan", "KAZ");
nameToAlpha03map.set("Kenya", "KEN");
nameToAlpha03map.set("Kosovo", "KSV");
nameToAlpha03map.set("Kyrgyzstan", "KGZ");
nameToAlpha03map.set("Cambodia", "KHM");
nameToAlpha03map.set("Kiribati", "KIR");
nameToAlpha03map.set("Saint Kitts and Nevis", "KNA");
nameToAlpha03map.set("South Korea", "KOR");
nameToAlpha03map.set("Kuwait", "KWT");
nameToAlpha03map.set("Laos", "LAO");
nameToAlpha03map.set("Lebanon", "LBN");
nameToAlpha03map.set("Liberia", "LBR");
nameToAlpha03map.set("Libya", "LBY");
nameToAlpha03map.set("Saint Lucia", "LCA");
nameToAlpha03map.set("Liechtenstein", "LIE");
nameToAlpha03map.set("Sri Lanka", "LKA");
nameToAlpha03map.set("Lesotho", "LSO");
nameToAlpha03map.set("Lithuania", "LTU");
nameToAlpha03map.set("Luxembourg", "LUX");
nameToAlpha03map.set("Latvia", "LVA");
nameToAlpha03map.set("Macao", "MAC");
nameToAlpha03map.set("Saint Martin (French part)", "MAF");
nameToAlpha03map.set("Morocco", "MAR");
nameToAlpha03map.set("Monaco", "MCO");
nameToAlpha03map.set("Moldova", "MDA");
nameToAlpha03map.set("Madagascar", "MDG");
nameToAlpha03map.set("Maldives", "MDV");
nameToAlpha03map.set("Mexico", "MEX");
nameToAlpha03map.set("Marshall Islands", "MHL");
nameToAlpha03map.set("North Macedonia", "MKD");
nameToAlpha03map.set("Mali", "MLI");
nameToAlpha03map.set("Malta", "MLT");
nameToAlpha03map.set("Myanmar", "MMR");
nameToAlpha03map.set("Montenegro", "MNE");
nameToAlpha03map.set("Mongolia", "MNG");
nameToAlpha03map.set("Northern Mariana Islands", "MNP");
nameToAlpha03map.set("Mozambique", "MOZ");
nameToAlpha03map.set("Mauritania", "MRT");
nameToAlpha03map.set("Montserrat", "MSR");
nameToAlpha03map.set("Martinique", "MTQ");
nameToAlpha03map.set("Mauritius", "MUS");
nameToAlpha03map.set("Malawi", "MWI");
nameToAlpha03map.set("Malaysia", "MYS");
nameToAlpha03map.set("Mayotte", "MYT");
nameToAlpha03map.set("Namibia", "NAM");
nameToAlpha03map.set("New Caledonia", "NCL");
nameToAlpha03map.set("Niger", "NER");
nameToAlpha03map.set("Norfolk Island", "NFK");
nameToAlpha03map.set("Nigeria", "NGA");
nameToAlpha03map.set("Nicaragua", "NIC");
nameToAlpha03map.set("Niue", "NIU");
nameToAlpha03map.set("Netherlands", "NLD");
nameToAlpha03map.set("Norway", "NOR");
nameToAlpha03map.set("Nepal", "NPL");
nameToAlpha03map.set("Nauru", "NRU");
nameToAlpha03map.set("New Zealand", "NZL");
nameToAlpha03map.set("Oman", "OMN");
nameToAlpha03map.set("Pakistan", "PAK");
nameToAlpha03map.set("Panama", "PAN");
nameToAlpha03map.set("Pitcairn", "PCN");
nameToAlpha03map.set("Peru", "PER");
nameToAlpha03map.set("Philippines", "PHL");
nameToAlpha03map.set("Palau", "PLW");
nameToAlpha03map.set("Papua New Guinea", "PNG");
nameToAlpha03map.set("Poland", "POL");
nameToAlpha03map.set("Puerto Rico", "PRI");
nameToAlpha03map.set("North Korea", "PRK");
nameToAlpha03map.set("Portugal", "PRT");
nameToAlpha03map.set("Paraguay", "PRY");
nameToAlpha03map.set("Palestine", "PSE");
nameToAlpha03map.set("French Polynesia", "PYF");
nameToAlpha03map.set("Qatar", "QAT");
nameToAlpha03map.set("Réunion", "REU");
nameToAlpha03map.set("Romania", "ROU");
nameToAlpha03map.set("Russia", "RUS");
nameToAlpha03map.set("Rwanda", "RWA");
nameToAlpha03map.set("Saudi Arabia", "SAU");
nameToAlpha03map.set("Sudan", "SDN");
nameToAlpha03map.set("Senegal", "SEN");
nameToAlpha03map.set("Singapore", "SGP");
nameToAlpha03map.set("South Georgia and the South Sandwich Islands", "SGS");
nameToAlpha03map.set("Saint Helena, Ascension and Tristan da Cunha", "SHN");
nameToAlpha03map.set("Svalbard and Jan Mayen", "SJM");
nameToAlpha03map.set("Solomon Islands", "SLB");
nameToAlpha03map.set("Sierra Leone", "SLE");
nameToAlpha03map.set("El Salvador", "SLV");
nameToAlpha03map.set("San Marino", "SMR");
nameToAlpha03map.set("Somalia", "SOM");
nameToAlpha03map.set("Saint Pierre and Miquelon", "SPM");
nameToAlpha03map.set("Serbia", "SRB");
nameToAlpha03map.set("South Sudan", "SSD");
nameToAlpha03map.set("Sao Tome and Principe", "STP");
nameToAlpha03map.set("São Tomé and Príncipe", "STP");
nameToAlpha03map.set("Suriname", "SUR");
nameToAlpha03map.set("Slovakia", "SVK");
nameToAlpha03map.set("Slovenia", "SVN");
nameToAlpha03map.set("Sweden", "SWE");
nameToAlpha03map.set("Eswatini", "SWZ");
nameToAlpha03map.set("Sint Maarten (Dutch part)", "SXM");
nameToAlpha03map.set("Seychelles", "SYC");
nameToAlpha03map.set("Syria", "SYR");
nameToAlpha03map.set("Turks and Caicos Islands", "TCA");
nameToAlpha03map.set("Chad", "TCD");
nameToAlpha03map.set("Togo", "TGO");
nameToAlpha03map.set("Thailand", "THA");
nameToAlpha03map.set("Tajikistan", "TJK");
nameToAlpha03map.set("Tokelau", "TKL");
nameToAlpha03map.set("Turkmenistan", "TKM");
nameToAlpha03map.set("Timor-Leste", "TLS");
nameToAlpha03map.set("East Timor", "TLS");
nameToAlpha03map.set("Tonga", "TON");
nameToAlpha03map.set("Trinidad and Tobago", "TTO");
nameToAlpha03map.set("Tunisia", "TUN");
nameToAlpha03map.set("Türkiye", "TUR");
nameToAlpha03map.set("Tuvalu", "TUV");
nameToAlpha03map.set("Taiwan", "TWN");
nameToAlpha03map.set("Republic of China (Taiwan)", "TWN");
nameToAlpha03map.set("Tanzania", "TZA");
nameToAlpha03map.set("Uganda", "UGA");
nameToAlpha03map.set("Ukraine", "UKR");
nameToAlpha03map.set("United States Minor Outlying Islands", "UMI");
nameToAlpha03map.set("Uruguay", "URY");
nameToAlpha03map.set("United States", "USA");
nameToAlpha03map.set("Uzbekistan", "UZB");
nameToAlpha03map.set("Holy See", "VAT");
nameToAlpha03map.set("Vatican City", "VAT");
nameToAlpha03map.set("Saint Vincent and the Grenadines", "VCT");
nameToAlpha03map.set("Venezuela", "VEN");
nameToAlpha03map.set("Virgin Islands (British)", "VGB");
nameToAlpha03map.set("Virgin Islands (U.S.)", "VIR");
nameToAlpha03map.set("Vietnam", "VNM");
nameToAlpha03map.set("Vanuatu", "VUT");
nameToAlpha03map.set("Wallis and Futuna", "WLF");
nameToAlpha03map.set("Samoa", "WSM");
nameToAlpha03map.set("Yemen", "YEM");
nameToAlpha03map.set("South Africa", "ZAF");
nameToAlpha03map.set("Zambia", "ZMB");
nameToAlpha03map.set("Zimbabwe", "ZWE");
nameToAlpha03map.set("Turkey", "TUR");

fs.readFile('stat.csv', (err, data) => {
    parse(data, {columns: false, trim: true}, (err, rows) => {
        if (err) {
            console.error(err);
            return;
        }

        console.log("{");
        console.log(`\"sid\": ${rows[1][0]},`);
        console.log(`\"name\": \"${rows[1][1]}\",`);
        console.log(`\"units\": \"${rows[1][2]}\",`);
        console.log(`\"count\": \"${rows.length-3}\",`);
        console.log(`\"rankings\": [`);

        for (let i = 3; i < rows.length; i++) {
            console.log("{");
            console.log(`\"rank\": ${rows[i][0]},`);
            
            const cid =  nameToAlpha03map.get(rows[i][1]);
            if (!!!cid) throw new Error(`Country \'${rows[i][1]}\' is not contained in map.`) 
            console.log(`\"cid\": \"${cid}\",`);
            console.log(`\"datum\": \"${rows[i][2]}\"`);
            console.log(`}${i == rows.length-1 ? "" : ","}`);
        }
        console.log("]");
        console.log("}");
    });
});